# -------------------------------------------------------------------------
# This is a per-user settings (overrides default and site settings):
#  Should be copied to ~/.spack/cray/config.yaml on piz daint
# -------------------------------------------------------------------------
config:
  # Temporary locations Spack can try to use for builds.
  # Spack will use the first one it finds that exists and is writable.
  # You can use $tempdir to refer to the system default temp directory
  # (as returned by tempfile.gettempdir()).
  # A value of $spack/var/spack/stage indicates that Spack should run
  # builds directly inside its install directory without staging them in
  # temporary space.
  # The build stage can be purged with `spack clean --stage`.
  build_stage:
    - ${XDG_RUNTIME_DIR}
    - $spack/.spack/var/stage
  # Cache directory for already downloaded source tarballs and archived
  # repositories. This can be purged with `spack clean --downloads`.
  source_cache: $spack/.spack/var/cache/source
  # Cache directory for miscellaneous files, like the package index.
  # This can be purged with `spack clean --misc-cache`
  misc_cache: $spack/.spack/var/cache/misc

